---
- name: Install and run apache
  hosts: slave
  become: true
  become_user: root
  gather_facts: true
  tasks:
    
    - name: Install service
      yum:
        name: apache2
        state: latest
    - name: Create content
      template:
        src: index.html
        dest: /var/www/html/index.html
    - name: Run service
      service:
        name: apache2
        state: started
